### ISSUE TITLE
Starting VM throws this error

### ISSUE THREAD

**Issue by revan1611** [BigAnteater/KVM-GPU-Passthrough#16]
```
Error starting domain: unsupported configuration: chardev 'spicevmc' not supported without spice graphics

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 1352, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: unsupported configuration: chardev 'spicevmc' not supported without spice graphics

```

**Comment by revan1611** [comment]
I get this error when I try to add/remove device or boot VM

**Comment by nemomode7** [comment]
Got the same error on manjaro. Decided to switch distro to Mint and use [https://gitlab.com/risingprismtv/single-gpu-passthrough/-/wikis/home](Risingprismtv's guide). Got it working. 

It would be interesting to know what caused the error though.

**Comment by NetuserPRO46** [comment]
Solution: Select Overview and select XML tab, find video and spice devices and delete them. Click Apply and error is gone!

**Comment by nemomode7** [comment]
It shows the same error when I push apply and reverts it back . I've found
a solution though. In XML audio should be set to "none" and then you can
remove the devices.

**Comment by maplepy** [comment]
doesn't work for me :/
