### ISSUE TITLE
libvirt.libvirtError: unsupported configuration: host doesn't support passthrough of host PCI devices

### ISSUE THREAD

**Issue by SamIsOnMC** [BigAnteater/KVM-GPU-Passthrough#19]
Error starting domain: unsupported configuration: host doesn't support passthrough of host PCI devices

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 1352, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: unsupported configuration: host doesn't support passthrough of host PCI devices

while trying to start my VM.

**Comment by SamIsOnMC** [comment]
21:44 sam@archpc /home/sam
% cat logs
error: internal error: qemu unexpectedly closed the monitor: 2022-07-02T19:41:18.784519Z qemu-system-x86_64: -device {"driver":"vfio-pci","host":"0000:09:00.0","id":"hostdev0","bus":"pci.1","addr":"0x0","romfile":"/usr/share/vgabios/gpu.rom"}: vfio 0000:09:00.0: group 2 is not viable
Please ensure all devices within the iommu_group are bound to their vfio bus driver.
21:44 sam@archpc /home/sam
%

**Comment by SamIsOnMC** [comment]
Got it fixed... sort of...

When going into my pc over ssh and doing sudo virsh start win10

It says Domain Started Win10 but my monitor just goes into standby. Help?
